<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/Chuong7%2B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#MSSV: 2174802010828  
#Họ và tên: Tạ Huỳnh Thy Anh
#Chương 7 + 8

In [ ]:
#Chương 7
#1. Giới thiệu một số ứng dụng của tích vector (dot product)

In [1]:
import numpy as np
signals = np.array([[1,2],[3,4],[10,0]])
sample = np.array([3,-1])
np.inner(signals, sample)

array([ 1,  5, 30])

In [2]:
#1.1 Ứng dụng 1 – Nguyên lý tìm nốt nhạc trong chuỗi âm thanh 
#Ví dụ 1
import numpy as np
A = np.array([0,0,-1,2,3,-1,0,1,-1,-1]) 
search_vector = np.array([0,1,-1])
len(A), len(search_vector)

(10, 3)

In [6]:
B = np.array([1])
B = np.resize(B, (len(A)-len(search_vector)+1, len(search_vector)))
B = np.asmatrix(B)
for i in range(len(A)-len(search_vector)+1): # so dong
  for j in range(len(search_vector)): # so cot 
    B[i,j] = A[i+j]

In [7]:
C = np.inner(B, search_vector)
for i in range(len(A)-len(search_vector)+1): 
  if ( C[0,i] == np.inner(search_vector, search_vector) ): 
    print (i, B[i])

6 [[ 0  1 -1]]


In [ ]:
#2.1.Đơn giản hóa thuật toán Pagerank

In [14]:
import numpy as np
A = np.array([[0,0,1.0/2, 1.0/2],
              [1.0/3,0,0,0], 
              [1.0/3,0,0,1.0/2], 
              [1.0/3,1.0,1.0/2,0]])
x = np.array([1,1,1,1])

In [16]:
x = np.dot(A, x) 
print (x)

[1.33333333 0.33333333 1.25       1.08333333]


In [19]:
x = np.array([1.0, 1.0, 1.0, 1.0]) 
for i in range(10):
  x = np.dot(A, x)
  print (i+1, x)

1 [1.         0.33333333 0.83333333 1.83333333]
2 [1.33333333 0.33333333 1.25       1.08333333]
3 [1.16666667 0.44444444 0.98611111 1.40277778]
4 [1.19444444 0.38888889 1.09027778 1.32638889]
5 [1.20833333 0.39814815 1.06134259 1.33217593]
6 [1.19675926 0.40277778 1.06886574 1.33159722]
7 [1.20023148 0.39891975 1.06471836 1.3361304 ]
8 [1.20042438 0.40007716 1.06814236 1.3313561 ]
9 [1.19974923 0.40014146 1.06581951 1.3342898 ]
10 [1.20005466 0.39991641 1.06706131 1.33296762]


In [ ]:
#Chương 8
#2.2.Bài toán ứng dụng: Ma trận biến đổi (ảnh/font chữ/...)

In [20]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T 
print (P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [21]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]]) 
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],
                           [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [22]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([-1,2])
P_cauc = (P.T + vecdelta).T 
print (P_cauc)

[[-1 -1  2  2  0  0  1  1  0  0]
 [ 2  7  7  6  6  5  5  4  4  2]]


In [27]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]]) 
vecdelta = np.array([1,2])
P_caud = (P.T @ matran_biendoi + vecdelta).T
print (P_caud)

[[1. 1. 4. 4. 2. 2. 3. 3. 2. 2.]
 [2. 7. 7. 6. 6. 5. 5. 4. 4. 2.]]
