<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/CHUONG1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Ho ten: Ta Huynh Thy Anh
#MSSV: 2174802010828
#Chuong1: SYMPY & NUMPY

In [2]:
#1.2.1 Các phép xử lý với danh sách
danhsach1 = [1., 3.]
danhsach2 = [5., 7.]
danhsach = danhsach1 + danhsach2

In [4]:
danhsach_gapdoi = 2*danhsach
danhsach_gapdoi

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [5]:
danhsach*2

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [6]:
danhsach/2

TypeError: ignored

In [7]:
mon_hoc = ['ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB']
thu_tu = [2,3,4,1]
diem_so = [10,9,8,7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
anh_xa

In [8]:
tap_hop = set(anh_xa)
tap_hop

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [9]:
lay_TT, lay_monhoc, lay_diem = zip(*anh_xa)
lay_monhoc

ValueError: ignored

In [10]:
import itertools
tap_sinh = list(itertools.chain(range(4), range(5,10), range(15,20)))
tap_sinh

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [11]:
list(zip(range(4), range(7,12), reversed(range(11))))

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

In [ ]:
#2.1 Dinh nghia Symbol va cac phep toan hinh thuc (symbolic)

In [12]:
from sympy import Symbol
x = Symbol('x')
f = x+x+x+2
f

3*x + 2

In [13]:
a = Symbol('Noi')
b = Symbol('Chim')
3*b + 7*a

3*Chim + 7*Noi

In [14]:
a = Symbol('Noi')
b = Symbol('Chim')
a.name

'Noi'

In [15]:
b.name

'Chim'

In [16]:
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

In [17]:
from sympy import symbols 
a,b,c = symbols('a,b,c')

In [18]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
s = x*y + y*x
s

2*x*y

In [19]:
p = x*(x+2*x)
p

3*x**2

In [20]:
p = (x+2)*(y+3)
p
(x + 2)*(y + 3)
p = (x+2)*(y+3) + (x+2)*(x-3)
p

(x - 3)*(x + 2) + (x + 2)*(y + 3)

In [21]:
p = x*(-x+2*x-x)
p

0

In [22]:
p = (x+2)*(y+3)
p.expand()

x*y + 3*x + 2*y + 6

In [ ]:
#2.2.1 Dat nhan tu chung va khai trien bieu thuc

In [23]:
from sympy import factor
bieuthuc = x**3 - y**3
factor(bieuthuc)

(x - y)*(x**2 + x*y + y**2)

In [24]:
 from sympy import expand
bieuthuc = (x - y)*(x**2 + x*y + y**2)
expand(bieuthuc)

x**3 - y**3

In [ ]:
#2.2.3 Thay the gia tri

In [25]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc

x**2 - x*y + y**2

In [26]:
giatri = bieuthuc.subs({x:3, y:2})
giatri

7

In [29]:
#Thuc hanh:
#Tinh huong 1
giatri = bieuthuc.subs({x:3, y:x})
giatri

x**2 - 3*x + 9

In [30]:
#Tinh huong 2
giatri = bieuthuc.subs({x:y, y:3})
giatri

9

In [31]:
#Tinh huong 3
giatri = bieuthuc.subs({y:x}).subs({x:3})
giatri

9

In [37]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc
bieuthuc_moi=bieuthuc.subs({x:1-y})
bieuthuc_moi

y**2 - y*(1 - y) + (1 - y)**2

In [38]:
from sympy import simplify
dongian = simplify(bieuthuc_moi)
dongian

3*y**2 - 3*y + 1

In [41]:
from sympy import Symbol
from sympy import sin, cos 
x = Symbol('x')
y = Symbol('y')
bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
bt_moi

sin(x + y)

In [51]:
#3.1 Mot so lenh co ban numpy xu ly vecto
import numpy as np
from numpy import *

In [44]:
vec1 = np.array([1., 3., 5.])
vec1 * 2

array([ 2.,  6., 10.])

In [45]:
vec1 * vec1

array([ 1.,  9., 25.])

In [46]:
vec1 /2

array([0.5, 1.5, 2.5])

In [47]:
vec1 + vec1

array([ 2.,  6., 10.])

In [53]:
vec2 = array([2., 4.]) 
vec1 + vec2

ValueError: ignored

In [54]:
vec3 = array([2., 4., 6.])
vec1 + vec3

array([ 3.,  7., 11.])

In [55]:
vec1 / vec3

array([0.5       , 0.75      , 0.83333333])

In [56]:
vec1 * vec3

array([ 2., 12., 30.])

In [57]:
2* vec1 + 5* vec3

array([12., 26., 40.])

In [58]:
vec3[2]

6.0

In [59]:
vec4 = np.linspace(0, 20, 5)
vec4

array([ 0.,  5., 10., 15., 20.])

In [60]:
vec5 = np.zeros(5)

In [61]:
vec6 = np.ones(5)

In [62]:
vec7 = np.empty(5)

In [63]:
np.rand(5)

AttributeError: ignored

In [65]:
v = np.array([1., 3., 5.])

In [66]:
np.sum(v)

9.0

In [67]:
 v.shape

(3,)

In [68]:
v.transpose()

array([1., 3., 5.])

In [69]:
v1 = v[:2]
v1

array([1., 3.])

In [70]:
v[0] = 5
v

array([5., 3., 5.])

In [71]:
v1

array([5., 3.])

In [72]:
v1[:2] = [1., 2., 3.]

ValueError: ignored

In [73]:
v1[:2] = [1., 2]
v

array([1., 2., 5.])

In [74]:
v3 = 2 * v[:2] + v1 * 3
v3

array([ 5., 10.])

In [75]:
v1 = [4, 6]
v3

array([ 5., 10.])

In [76]:
v

array([1., 2., 5.])

In [77]:
v + 10.0

array([11., 12., 15.])

In [78]:
np.sqrt(v)

array([1.        , 1.41421356, 2.23606798])

In [79]:
np.cos(v)

array([ 0.54030231, -0.41614684,  0.28366219])

In [80]:
np.sin(v)

array([ 0.84147098,  0.90929743, -0.95892427])

In [81]:
np.dot(v1, v3)

80.0

In [82]:
v1.dot(v3)

AttributeError: ignored

In [83]:
v3.dot(v1)

80.0

In [ ]:
#Bai tap chuong 1

In [84]:
#Bai tap 1: Giai phuong trinh voi Sympy
from sympy import Symbol, solve
x = Symbol('x')
bieuthuc = x + 3 - 5
solve(bieuthuc)

[2]

In [85]:
bieuthuc = x**2 + 3 - 5
nghiemx = solve(bieuthuc)
nghiemx

[-sqrt(2), sqrt(2)]

In [86]:
nghiemx[0]

-sqrt(2)

In [87]:
nghiemx[1]

sqrt(2)

In [88]:
#Bai tap 2: Giai phuong trinh bac 2
from sympy import solve
x = Symbol('x')
ptb2 = x**2 + 9*x +8
solve(ptb2, dict = True)

[{x: -8}, {x: -1}]

In [89]:
ptb2 = x**2 + 1*x + 10
nghiemx = solve(ptb2, dict = True)
nghiemx

[{x: -1/2 - sqrt(39)*I/2}, {x: -1/2 + sqrt(39)*I/2}]

In [90]:
#Bai tap 3: Giai phuong trinh 1 bien bieu dien dai so cac bien con lai
x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
ptb2 = a*x*x + b*x + c
nghiem = solve(ptb2, x, dict=True)
nghiem

[{x: (-b + sqrt(-4*a*c + b**2))/(2*a)}, {x: -(b + sqrt(-4*a*c + b**2))/(2*a)}]

In [91]:
#Bai tap 4: Giai he phuong trinh
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
pt1 = 2*x+3*y-12
pt2 = 3*x-2*y-5

In [92]:
solve((pt1, pt2), dict=True)

[{x: 3, y: 2}]

In [93]:
nghiem = solve((pt1, pt2), dict=True)
nghiem = nghiem[0]
pt1.subs({x:nghiem[x], y:nghiem[y]})

0

In [94]:
pt2.subs({x:nghiem[x], y:nghiem[y]})

0

In [95]:
#Bai tap 5: The hien ma tran bang numpy
M1 = np.array([ [9, 12], [23,30] ])

In [96]:
u = np.array([ 2, 1])
tichM1u = M1.dot(u)
print(tichM1u)

[30 76]


In [97]:
tichuM1 = u.dot(M1)
print(tichuM1)

[41 54]


In [98]:
np.dot(M1, u)

array([30, 76])

In [99]:
np.dot(u, M1)

array([41, 54])

In [102]:
mat1 = np.zeros( [5,5])
mat1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [103]:
mat2 = np.ones( [5,5])
mat2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
mat3 = mat1 + 2* mat2
mat3

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [105]:
mat4 = mat3
mat3[3][2] = 10
mat3
mat4

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [107]:
mat5 = np.copy(mat3)
mat3[3][2] = 10
mat3
mat4
mat5

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [108]:
mat6 = np.empty([4, 5])
mat6

array([[1.96781208e-316, 1.10343781e-312, 1.29441743e-312,
        2.31297541e-312, 2.46151512e-312],
       [2.12199579e-313, 2.05833592e-312, 1.08221785e-312,
        1.08221785e-312, 1.93101617e-312],
       [1.97345609e-312, 1.29441743e-312, 1.03977794e-312,
        2.12199579e-313, 2.05833592e-312],
       [1.08221785e-312, 2.31297541e-312, 2.46151512e-312,
        1.08221785e-312, 0.00000000e+000]])

In [109]:
 mat7 = np.identity(4)
 mat7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [111]:
mat8 = np.random.random([4,5])
mat8

array([[0.64753644, 0.24479328, 0.1991399 , 0.8340427 , 0.51483469],
       [0.3993358 , 0.21341014, 0.96610063, 0.86186601, 0.37597649],
       [0.14444258, 0.41077066, 0.54940658, 0.29042389, 0.33434321],
       [0.42439293, 0.06326481, 0.48671406, 0.82059265, 0.442954  ]])