<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/Chuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Họ và tên: Tạ Huỳnh Thy Anh
#MSSV: 2174802010828
#Chương 5: Định thức, ma trận và ứng dụng

In [ ]:
#Bài tập 1

In [ ]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] 
M = np.mat([[1,2],[3,4]]) 
for i in range(len(c)):
  ci = np.mat([[1,1],[1,0]]) 
  ci[0, 0] = c[i]
  if (i==0):
    M = ci 
  else:
    M = M.dot(ci) 
print(M)
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [ ]:
#Vậy số Pi = 3.1415926535897936

In [ ]:
#Bài tập 2

In [ ]:
import numpy as np
from scipy import linalg

In [ ]:
X = np.array([[1,1],[1,2],[1,3],[1,4],[1,5]])
X

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [ ]:
Y = np.array([[1],[2],[4],[4],[6]])
Y

array([[1],
       [2],
       [4],
       [4],
       [6]])

In [ ]:
XT = X.T
XT

array([[1, 1, 1, 1, 1],
       [1, 2, 3, 4, 5]])

In [ ]:
A1 = linalg.inv(XT.dot(X))
A1

array([[ 1.1, -0.3],
       [-0.3,  0.1]])

In [ ]:
A2 = XT.dot(Y)
A2

array([[17],
       [63]])

In [ ]:
A = A1.dot(A2)
A

array([[-0.2],
       [ 1.2]])

In [ ]:
#Vậy phương trình đường thẳng tuyến tính bậc 1 là f(x) = -0,2 + 1,2x

In [ ]:
E = Y - (X.dot(A))
E

array([[-1.77635684e-15],
       [-2.00000000e-01],
       [ 6.00000000e-01],
       [-6.00000000e-01],
       [ 2.00000000e-01]])

In [ ]:
ET = E.T
ET

array([[-1.77635684e-15, -2.00000000e-01,  6.00000000e-01,
        -6.00000000e-01,  2.00000000e-01]])

In [ ]:
e = ET.dot(E)
e

array([[0.8]])

In [ ]:
#Vậy sai số e là: 0,8

In [ ]:
#Bài tập 3

In [ ]:
def bpcuctieu(a):
  b = []
  o1 = []
  for i in range(len(a)):
    o1.append(1.0)
    b.append((i+0)*1.0)
  x = np.array([o1, b]) 
  u = np.dot(x, x.T) 
  y = np.array(a)
  from numpy import linalg
  u_1 =np.linalg.inv(u)
  v = np.dot(u_1, x) 
  A = np.dot(v, y)
  return A

In [ ]:
dulieu = [10, 8, 7, 5, 2]
bpcuctieu(dulieu)

array([10.2, -1.9])

In [ ]:
#Phương trình tuyến tính là: f(x) = 10,2 - 1,9x 
#Sai số là: 1,1