<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/CHUONG1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Ho ten: Ta Huynh Thy Anh
#MSSV: 2174802010828
#Chuong1: SYMPY & NUMPY

In [2]:
#1.2.1 Các phép xử lý với danh sách
danhsach1 = [1., 3.]
danhsach2 = [5., 7.]
danhsach = danhsach1 + danhsach2

In [4]:
danhsach_gapdoi = 2*danhsach
danhsach_gapdoi

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [5]:
danhsach*2

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [6]:
danhsach/2

TypeError: ignored

In [7]:
mon_hoc = ['ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB']
thu_tu = [2,3,4,1]
diem_so = [10,9,8,7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
anh_xa

In [8]:
tap_hop = set(anh_xa)
tap_hop

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [9]:
lay_TT, lay_monhoc, lay_diem = zip(*anh_xa)
lay_monhoc

ValueError: ignored

In [10]:
import itertools
tap_sinh = list(itertools.chain(range(4), range(5,10), range(15,20)))
tap_sinh

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [11]:
list(zip(range(4), range(7,12), reversed(range(11))))

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

In [ ]:
#2.1 Dinh nghia Symbol va cac phep toan hinh thuc (symbolic)

In [12]:
from sympy import Symbol
x = Symbol('x')
f = x+x+x+2
f

3*x + 2

In [13]:
a = Symbol('Noi')
b = Symbol('Chim')
3*b + 7*a

3*Chim + 7*Noi

In [14]:
a = Symbol('Noi')
b = Symbol('Chim')
a.name

'Noi'

In [15]:
b.name

'Chim'

In [16]:
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

In [17]:
from sympy import symbols 
a,b,c = symbols('a,b,c')

In [18]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
s = x*y + y*x
s

2*x*y

In [19]:
p = x*(x+2*x)
p

3*x**2

In [20]:
p = (x+2)*(y+3)
p
(x + 2)*(y + 3)
p = (x+2)*(y+3) + (x+2)*(x-3)
p

(x - 3)*(x + 2) + (x + 2)*(y + 3)

In [21]:
p = x*(-x+2*x-x)
p

0

In [22]:
p = (x+2)*(y+3)
p.expand()

x*y + 3*x + 2*y + 6

In [ ]:
#2.2.1 Dat nhan tu chung va khai trien bieu thuc

In [23]:
from sympy import factor
bieuthuc = x**3 - y**3
factor(bieuthuc)

(x - y)*(x**2 + x*y + y**2)

In [24]:
 from sympy import expand
bieuthuc = (x - y)*(x**2 + x*y + y**2)
expand(bieuthuc)

x**3 - y**3

In [ ]:
#2.2.3 Thay the gia tri

In [25]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc

x**2 - x*y + y**2

In [26]:
giatri = bieuthuc.subs({x:3, y:2})
giatri

7

In [29]:
#Thuc hanh:
#Tinh huong 1
giatri = bieuthuc.subs({x:3, y:x})
giatri

x**2 - 3*x + 9

In [30]:
#Tinh huong 2
giatri = bieuthuc.subs({x:y, y:3})
giatri

9

In [31]:
#Tinh huong 3
giatri = bieuthuc.subs({y:x}).subs({x:3})
giatri

9

In [37]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc
bieuthuc_moi=bieuthuc.subs({x:1-y})
bieuthuc_moi

y**2 - y*(1 - y) + (1 - y)**2

In [38]:
from sympy import simplify
dongian = simplify(bieuthuc_moi)
dongian

3*y**2 - 3*y + 1

In [41]:
from sympy import Symbol
from sympy import sin, cos 
x = Symbol('x')
y = Symbol('y')
bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
bt_moi

sin(x + y)

In [51]:
#3.1 Mot so lenh co ban numpy xu ly vecto
import numpy as np
from numpy import *

In [44]:
vec1 = np.array([1., 3., 5.])
vec1 * 2

array([ 2.,  6., 10.])

In [45]:
vec1 * vec1

array([ 1.,  9., 25.])

In [46]:
vec1 /2

array([0.5, 1.5, 2.5])

In [47]:
vec1 + vec1

array([ 2.,  6., 10.])

In [53]:
vec2 = array([2., 4.]) 
vec1 + vec2

ValueError: ignored

In [54]:
vec3 = array([2., 4., 6.])
vec1 + vec3

array([ 3.,  7., 11.])

In [55]:
vec1 / vec3

array([0.5       , 0.75      , 0.83333333])

In [56]:
vec1 * vec3

array([ 2., 12., 30.])

In [57]:
2* vec1 + 5* vec3

array([12., 26., 40.])