<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/Ch%C6%B0%C6%A1ng_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Thực hành 1

In [1]:
x = 3
print(x)

3


In [2]:
import math
x = math.sqrt(1+x)
print(x)

2.0


In [3]:
import math
x = math.sqrt(1+x)
print(x)

1.7320508075688772


In [4]:
import math
x = math.sqrt(1+x)
print(x)

1.6528916502810695


In [5]:
import math
x = math.sqrt(x)
print(x)

1.2856483384973783


Thực hành 2

In [6]:
import math
x = 3
lap = 1
while (x != math.sqrt(x + 1)):
  x = math.sqrt(x + 1)
  lap += 1
x

1.618033988749895

In [7]:
lap

32

Thực hành 3

In [8]:
import sympy as sp
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1 + x), x)

[1/2 + sqrt(5)/2]

Thực hành 4

In [9]:
import numpy as np
v1 = np.array([1.,2.,3.]) # tao vector 3 chieu
v2 = np.array([2.,1.,0.])
v3 = v1 + v2 # cong vector
v3

array([3., 3., 3.])

In [10]:
3*v1 + 2*v2

array([7., 8., 9.])

In [11]:
[1,2,3] + [2,1,0]

[1, 2, 3, 2, 1, 0]

In [12]:
3*[1,2,3] + 2*[2,1,0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [13]:
v4 = np.hstack([v1, v2])
v4

array([1., 2., 3., 2., 1., 0.])

In [14]:
np.dot(v1,v2)

4.0

In [15]:
angles = np.linspace(0, np.pi/2, 5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

Thực hành 5

In [16]:
import numpy as np
goc = np.pi/3
A = np.array([ [np.cos(goc), -np.sin(goc)], [np.sin(goc), np.cos(goc)] ])
V = np.array([1., 0.])
Y = np.dot(A, V)
Y

array([0.5      , 0.8660254])

Thực hành 6

In [17]:
from numpy import diff
dx = 0.1
y = [1, 2, 3, 4, 4, 5, 6]
dy = diff(y)/dx
dy

array([10., 10., 10.,  0., 10., 10.])

In [18]:
z = np.array([1,2,3,4,4,5,6])
dz = diff(z)/dx
dz

array([10., 10., 10.,  0., 10., 10.])

In [19]:
from numpy import diff
x = [.1, .2, .5, .6, .7, .8, .9]
y = [1,2,3,4,4,5,6]
dydx = diff(y)/diff(x)
print(dydx)

[10.          3.33333333 10.          0.         10.         10.        ]


Thực hành 7

In [20]:
from sympy.geometry import *

In [22]:
P1 = Point(0,0)
P2 = Point(3,4)
P3 = Point(2,-1)
P4 = Point(-1,-5)

In [23]:
S1 = Segment(P1,P2)
S2 = Segment(P3,P4)

In [24]:
Point.is_collinear(P1,P2,P3)

False

In [25]:
S1.length

5

In [26]:
S2.midpoint

Point2D(1/2, -3)

In [27]:
S1.slope

4/3

In [28]:
S1.intersection(S2)

[]

In [29]:
Segment.angle_between(S1,S2)

pi

In [30]:
S1.contains(P3)

False

In [31]:
L1 = Line(P1,P2)
L1.equation()

-4*x + 3*y

In [32]:
L1.is_parallel(S1)

True

In [33]:
L1.is_parallel(S2)

True

Thực hành 8