<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/Ch%C6%B0%C6%A1ng_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Họ tên: Tạ Huỳnh Thy Anh
#MSSV: 2174802010828
#CHUONG 2: Ma trận và hệ phương trình tuyến tính

In [ ]:
#1. Dẫn nhập - một số hàm về xử lý vector với python

In [3]:
def scale(a,v):
  return [a*vi for vi in v]
v = [3,5,7]
scale(10,v)

[30, 50, 70]

In [5]:
def sumvector(v,w):
  return [vi+wi for (vi,wi) in zip(v,w)]
v = [3,5,7]
w = [2,4,6] 
sumvector(v,w)

[5, 9, 13]

In [6]:
def dotvector(v,w):
  return sum([vi*wi for (vi,wi) in zip(v,w)])
dotvector(v,w)

68

In [7]:
def lenvector(v):
  return dotvector(v,v)
lenvector(w)

56

In [ ]:
#2. Bai toan ung dung 1 - Phan loai tuyen tinh

In [8]:
import numpy as np

In [11]:
scores = np.array([-1,1,2,-3,5,-4])

In [12]:
scores >= 0

array([False,  True,  True, False,  True, False])

In [13]:
scores < 0

array([ True, False, False,  True, False,  True])

In [14]:
np.select ([scores >= 0, scores <0], ['so duong', 'so am'])

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [15]:
scores = np.array([-1,1,2,0,-3,5,0,-4])
np.select([scores >0, scores ==0, scores <0],['so duong','so 0', 'so am'])

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [ ]:
#3. Thuc hanh xu ly ma tran
#3.1. Co ban ve xu ly ma tran

In [16]:
import numpy as np
from scipy import linalg, sparse

In [19]:
D = np.mat([[3,4],[5,6]])
print(D)

[[3 4]
 [5 6]]


In [21]:
C = np.mat(np.random.random((5,7)))
print(C)

[[0.98579937 0.18646229 0.88890494 0.99648737 0.32611248 0.09677251
  0.66101981]
 [0.29932775 0.26617851 0.34872563 0.54630996 0.33100842 0.26642591
  0.89354984]
 [0.1641845  0.46219085 0.87854013 0.00274174 0.75444647 0.13521533
  0.46473456]
 [0.69449427 0.24844971 0.57334038 0.06653516 0.58865043 0.89439292
  0.15081279]
 [0.91609192 0.78149853 0.30361242 0.57027768 0.72414314 0.35475505
  0.05154593]]


In [22]:
A = np.mat(np.random.random((2,2)))
print(A)

[[0.66005303 0.77059013]
 [0.43324318 0.38749674]]


In [23]:
b = np.array([1+5j, 2j, 3j,(4,5,6)])
B = np.asmatrix(b)
print(b)
print(B)

[(1+5j) 2j 3j (4, 5, 6)]
[[(1+5j) 2j 3j (4, 5, 6)]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [24]:
A.T

matrix([[0.66005303, 0.43324318],
        [0.77059013, 0.38749674]])

In [25]:
A.I

matrix([[-4.96252938,  9.86866668],
        [ 5.54838736, -8.45305833]])

In [26]:
linalg.inv(A)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [ ]:
M = np.array