<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/Ch%C6%B0%C6%A1ng_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Họ tên: Tạ Huỳnh Thy Anh
#MSSV: 2174802010828
#CHUONG 2: Ma trận và hệ phương trình tuyến tính

In [ ]:
#1. Dẫn nhập - một số hàm về xử lý vector với python

In [3]:
def scale(a,v):
  return [a*vi for vi in v]
v = [3,5,7]
scale(10,v)

[30, 50, 70]

In [5]:
def sumvector(v,w):
  return [vi+wi for (vi,wi) in zip(v,w)]
v = [3,5,7]
w = [2,4,6] 
sumvector(v,w)

[5, 9, 13]

In [6]:
def dotvector(v,w):
  return sum([vi*wi for (vi,wi) in zip(v,w)])
dotvector(v,w)

68

In [7]:
def lenvector(v):
  return dotvector(v,v)
lenvector(w)

56

In [ ]:
#2. Bai toan ung dung 1 - Phan loai tuyen tinh

In [8]:
import numpy as np

In [11]:
scores = np.array([-1,1,2,-3,5,-4])

In [12]:
scores >= 0

array([False,  True,  True, False,  True, False])

In [13]:
scores < 0

array([ True, False, False,  True, False,  True])

In [14]:
np.select ([scores >= 0, scores <0], ['so duong', 'so am'])

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [15]:
scores = np.array([-1,1,2,0,-3,5,0,-4])
np.select([scores >0, scores ==0, scores <0],['so duong','so 0', 'so am'])

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [ ]:
#3. Thuc hanh xu ly ma tran
#3.1. Co ban ve xu ly ma tran

In [16]:
import numpy as np
from scipy import linalg, sparse

In [19]:
D = np.mat([[3,4],[5,6]])
print(D)

[[3 4]
 [5 6]]


In [21]:
C = np.mat(np.random.random((5,7)))
print(C)

[[0.98579937 0.18646229 0.88890494 0.99648737 0.32611248 0.09677251
  0.66101981]
 [0.29932775 0.26617851 0.34872563 0.54630996 0.33100842 0.26642591
  0.89354984]
 [0.1641845  0.46219085 0.87854013 0.00274174 0.75444647 0.13521533
  0.46473456]
 [0.69449427 0.24844971 0.57334038 0.06653516 0.58865043 0.89439292
  0.15081279]
 [0.91609192 0.78149853 0.30361242 0.57027768 0.72414314 0.35475505
  0.05154593]]


In [22]:
A = np.mat(np.random.random((2,2)))
print(A)

[[0.66005303 0.77059013]
 [0.43324318 0.38749674]]


In [23]:
b = np.array([1+5j, 2j, 3j,(4,5,6)])
B = np.asmatrix(b)
print(b)
print(B)

[(1+5j) 2j 3j (4, 5, 6)]
[[(1+5j) 2j 3j (4, 5, 6)]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [24]:
A.T

matrix([[0.66005303, 0.43324318],
        [0.77059013, 0.38749674]])

In [25]:
A.I

matrix([[-4.96252938,  9.86866668],
        [ 5.54838736, -8.45305833]])

In [26]:
linalg.inv(A)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [27]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [29]:
M = np.array([[-1,3,2],[0,-2,1], [1,5,-2]])
v_diag = np.diag(M)
print(v_diag)
M_diag = np.diag(v_diag)
print(M_diag)

[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [30]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z])

[(2, 7, -1)]

In [34]:
x = [1,2,3]
y = [1,2,3]
print(all([x[i]==y[i] for i in range(len(x))]))

True


In [35]:
y = [1,2,4]
print(all([x[i]==y[i] for i in range(len(x))]))

False


In [36]:
import numpy as np
np.array_equal([1,2], [1,2])

True

In [37]:
np.array_equal(np.array([1,2]), np.array([1,2]))

True

In [ ]:
#3.2 cac phep bien doi so cap tren ma tran

In [39]:
A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [40]:
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [41]:
A.size

36

In [42]:
np.matrix.diagonal(A)

array([ 0.,  7., 14., 21., 28., 35.])

In [43]:
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [44]:
vecB = np.array([1.,2.,3.,4.,5.,6.])
C = A.dot(vecB)
print(C)

[ 71. 198. 325. 452. 579. 706.]


In [48]:
D = np.array([[1.,2.,3.,4.,5.,6.],[1.,0.,1.,0.,1.,0.]])
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [52]:
E = D.dot(A)
print(E)

[[421. 443. 465. 487. 509. 531.]
 [ 37.  39.  43.  45.  49.  51.]]


In [53]:
F = np.array([[1.,1.],[2.,0.],[3.,1.],[4.,0],[5.,1],[6.,0.]])
G = A.dot(F)
print(F)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [54]:
print(G)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [55]:
np.linalg.inv(A)

array([[ 0.37022901, -0.45610687, -0.28244275, -0.10877863,  0.0648855 ,
         0.23854962],
       [-0.44656489,  0.65839695, -0.23664122, -0.13167939, -0.02671756,
         0.07824427],
       [-0.26335878, -0.22709924,  0.80916031, -0.15458015, -0.11832061,
        -0.08206107],
       [-0.08015267, -0.11259542, -0.14503817,  0.82251908, -0.20992366,
        -0.24236641],
       [ 0.10305344,  0.0019084 , -0.09923664, -0.20038168,  0.69847328,
        -0.40267176],
       [ 0.28625954,  0.11641221, -0.05343511, -0.22328244, -0.39312977,
         0.4370229 ]])

In [56]:
np.linalg.inv(np.linalg.inv(A))

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

In [ ]:
#4. Bai toan ung dung 2 - Tinh toan day Fibonacci

In [59]:
import numpy as np
A = np.array([[1,1],[1,0]])
b = np.array([1,0])
n = 10
for i in range(n):
  b = A.dot(b)
print(b)

[89 55]


In [ ]:
#5. Co ban ve he phuong trinh tuyen tinh va ung dung minh hoa

In [ ]:
#5.1 Làm quen với giải hệ phương trình tuyến tính

In [ ]:
#5.2 Bài toán ứng dụng 3 - Đếm số lượng xe vào khu vực trung tâm

In [60]:
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1,pt2,pt3,pt4))
nghiem

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [65]:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])

In [66]:
A_nghichdao = np.linalg.inv(A)

LinAlgError: ignored

In [ ]:
#BAI TAP CHUONG 2

In [ ]:
#Cau 1: Hay su dung numpy de giai cac phuong trinh
#Van de 1:

In [67]:
import numpy as np
A = np.matrix([[1,-1],[2,3]])
A

matrix([[ 1, -1],
        [ 2,  3]])

In [69]:
A_nghich = np.invert(A)
b = np.array([-2,6])
nghiem = A_nghich.dot(b)
nghiem

matrix([[  4, -18]])

In [70]:
#van de 2:
import numpy as np
A = np.matrix([[1,-1,0],[2,-1,-1], [1,1,1]])
A

matrix([[ 1, -1,  0],
        [ 2, -1, -1],
        [ 1,  1,  1]])

In [71]:
A_ngd = np.invert(A)
b = np.array([2,3,6])
nghiem = A_ngd.dot(b)
nghiem

matrix([[-10,  -6, -22]])

In [72]:
#van de 3
import numpy as np
A = np.matrix([[1,1,1], [4,2,1], [9,3,1]])
A

matrix([[1, 1, 1],
        [4, 2, 1],
        [9, 3, 1]])

In [73]:
A_ngd = np.invert(A)
b = np.array([4,3,4])
nghiem = A_ngd.dot(b)
nghiem

matrix([[-22, -37, -60]])

In [77]:
#van de 4
import numpy as np
A = np.matrix([[1,0,1], [1,1,-2], [-2,2,1]])
A

matrix([[ 1,  0,  1],
        [ 1,  1, -2],
        [-2,  2,  1]])

In [78]:
A_ngd = np.invert(A)
b = np.array([1,-3,0])
nghiem = A_ngd.dot(b)
nghiem

matrix([[ 1,  4, 10]])

In [79]:
#cau2
#van_de_1
import sympy as sp
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
pt1 = x - y + 2
pt2 = 2*x + 3*y - 6
nghiem = sp.solve((pt1,pt2))
nghiem

{x: 0, y: 2}

In [80]:
#van_de_2
import sympy as sp
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')
pt1 = x - y - 2
pt2 = 2*x - y - z - 3
pt3 = x + y + z -6
nghiem = sp.solve((pt1,pt2,pt3))
nghiem

{x: 3, y: 1, z: 2}

In [81]:
#van_de_3
import sympy as sp
from sympy import Symbol, solve
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
pt1 = a + b + c - 4
pt2 = 4*a + 2*b + c - 3
pt3 = 9*a + 3*b + c -4
nghiem = sp.solve((pt1,pt2,pt3))
nghiem

{a: 1, b: -4, c: 7}

In [82]:
#van_de_4
import sympy as sp
from sympy import Symbol, solve
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
pt1 = a + c - 1
pt2 = a + b - 2*c + 3
pt3 = -2*a + 2*b + c 
nghiem = sp.solve((pt1,pt2,pt3))
nghiem

{a: -1/9, b: -2/3, c: 10/9}

In [83]:
#cau3
import numpy as np
A = np.array([[1,1], [1, 0]])
b = np.array([0,0])
n = 3

In [85]:
for i in range(n):
  b = A.dot(b)
  print(b)

[0 0]
[0 0]
[0 0]
