<a href="https://colab.research.google.com/github/ThyAnhhh/ThuchanhToanCC/blob/main/Ch%C6%B0%C6%A1ng_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#MSSV: 2174802010828
#Họ và tên: Tạ Huỳnh Thy Anh
#Chương 3: Ma trận và hệ phương trình tuyến tính

In [ ]:
#1. Tóm tắt một số phép xử lý ma trận của Numpy với Scipy
#1.1 Một số phép xử lý ma trận của Numpy với Scipy

In [4]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])

In [7]:
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b)
C = np.mat(np.random.random( (10,5) ) )
D = np.mat([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)

In [9]:
F = np.eye(3, k=0)
F = np.eye(3, k=-1)

In [10]:
F

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [13]:
np.linalg.matrix_rank(C)

5

In [14]:
A.I

matrix([[-4.49697941,  4.92246174],
        [ 7.89793228, -6.27042244]])

In [15]:
 linalg.inv(A)

array([[-4.49697941,  4.92246174],
       [ 7.89793228, -6.27042244]])

In [16]:
linalg.det(A)

-0.09363901797684503

In [17]:
A.T

matrix([[0.5871562 , 0.73955462],
        [0.46093448, 0.42109274]])

In [18]:
A.H

matrix([[0.5871562 , 0.73955462],
        [0.46093448, 0.42109274]])

In [19]:
linalg.solve(A, b)

array([[-4.49697941-20.78296768j,  0.        +15.61834991j,
         0.        +16.04383225j],
       [ 7.89793228+45.99970075j,  0.        -15.55624765j,
         0.        -13.92873781j]])

In [23]:
E = np.mat(a).T

In [22]:
linalg.lstsq(F, E)

(array([[2.],
        [3.],
        [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))

In [24]:
np.add(A, D)

matrix([[4.5871562 , 3.46093448],
        [2.73955462, 6.42109274]])

In [25]:
np.subtract(A, D)

matrix([[-3.4128438 , -2.53906552],
        [-1.26044538, -5.57890726]])

In [26]:
np.divide(A, D)

matrix([[0.14678905, 0.15364483],
        [0.36977731, 0.07018212]])

In [27]:
A @ D

matrix([[3.27049377, 4.5270755 ],
        [3.80040396, 4.74522028]])

In [28]:
np.multiply(D, A)

matrix([[2.3486248 , 1.38280345],
        [1.47910925, 2.52655641]])

In [29]:
np.dot(A, D)

matrix([[3.27049377, 4.5270755 ],
        [3.80040396, 4.74522028]])

In [30]:
np.vdot(A, D)

matrix([[2.3486248]])

In [31]:
linalg.expm(A)

array([[2.09742694, 0.8081004 ],
       [1.29657122, 1.80628805]])

In [32]:
linalg.logm(A)

array([[-1.00479905+1.34963389j,  0.99565441-1.22774017j],
       [ 1.59749562-1.9698698j , -1.36350907+1.79195876j]])

In [ ]:
#4. Bài toán ứng dụng 1 
#Căn bản về mật mã học, mã hoá thông tin, mật khẩu

In [37]:
from scipy import linalg
import numpy as np

In [38]:
E = np.array([[1,-2,2],[-1,1,3],[1,-1,-4]])
E

array([[ 1, -2,  2],
       [-1,  1,  3],
       [ 1, -1, -4]])

In [51]:
KHO = np.matrix([13,11,17])
kq_KHO = KHO.dot(E)
kq_KHO

matrix([[ 19, -32,  -9]])

In [52]:
A_H = np.matrix([1,0,11])
kq_A_H = A_H.dot(E)
kq_A_H

matrix([[ 12, -13, -42]])

In [53]:
O_C = np.matrix([17,34,5])
kq_O_C = O_C.dot(E)
kq_O_C

matrix([[-12,  -5, 116]])

In [64]:
_DƯ = np.matrix([0,6,26])
kq_DƯ = _DƯ.dot(E)
kq_DƯ

matrix([[ 20, -20, -86]])

In [55]:
L = np.matrix([33,0,14])
kq_L = L.dot(E)
kq_L

matrix([[ 47, -80,  10]])

In [56]:
IÊ = np.matrix([12,9,34])
kq_IÊ = IÊ.dot(E)
kq_IÊ

matrix([[ 37, -49, -85]])

In [57]:
U = np.matrix([25,35,35])
kq_U = U.dot(E)
kq_U

matrix([[ 25, -50,  15]])

In [58]:
E_ = linalg.inv(E)
E_

array([[ -1., -10.,  -8.],
       [ -1.,  -6.,  -5.],
       [  0.,  -1.,  -1.]])

In [ ]:
#Giải mã

In [60]:
kq_KHO.dot(E_)

matrix([[13., 11., 17.]])

In [61]:
kq_A_H.dot(E_)

matrix([[ 1.,  0., 11.]])

In [62]:
kq_O_C.dot(E_)

matrix([[17., 34.,  5.]])

In [65]:
kq_DƯ.dot(E_)

matrix([[ 0.,  6., 26.]])

In [66]:
kq_L.dot(E_)

matrix([[33.,  0., 14.]])

In [67]:
kq_IÊ.dot(E_)

matrix([[12.,  9., 34.]])

In [68]:
kq_U.dot(E_)

matrix([[25., 35., 35.]])

In [ ]:
#Bài tập chương 1
#Câu 1: Hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để

In [ ]:
#a. Tự chọn một ma trận khả nghịch 3x3. Sinh viên 
#chứng minh ma trận đó khả nghịch (tồn tại ma trận nghịch đảo)

In [69]:
from scipy import linalg
import numpy as np

In [88]:
A = np.array([[1,-2,1],[-1,2,1],[1,-1,4]])
A

array([[ 1, -2,  1],
       [-1,  2,  1],
       [ 1, -1,  4]])

In [89]:
A_ = linalg.inv(A)
A_

array([[-4.5, -3.5,  2. ],
       [-2.5, -1.5,  1. ],
       [ 0.5,  0.5,  0. ]])

In [ ]:
#b. Nhập họ và tên hoặc mã số sinh viên (của sinh viên).
#c. Mã hóa họ và tên hoặc mã số sinh viên 
#d. Thực hiện giải mã với ma trận được chọn.
# T  A  .  H  U  Y  '  N  H  T  H  Y  A  N  H
# 24 01 34 11 25 29 31 16 11 24 11 29 01 16 11

In [108]:
TA = np.matrix([24,1,34])
kq1 = TA.dot(A)
kq1

matrix([[ 57, -80, 161]])

In [109]:
HUY = np.matrix([11,25,29])
kq2 = HUY.dot(A)
kq2

matrix([[ 15,  -1, 152]])

In [110]:
NH = np.matrix([31,16,11])
kq3 = NH.dot(A)
kq3

matrix([[ 26, -41,  91]])

In [111]:
THY = np.matrix([24,11,29])
kq4 = THY.dot(A)
kq4

matrix([[ 42, -55, 151]])

In [112]:
ANH = np.matrix([1,16,11])
kq5 = ANH.dot(A)
kq5

matrix([[-4, 19, 61]])

In [ ]:
#Giai ma

In [114]:
kq1.dot(A_)

matrix([[24.,  1., 34.]])

In [113]:
kq2.dot(A_)

matrix([[11., 25., 29.]])

In [115]:
kq3.dot(A_)

matrix([[31., 16., 11.]])

In [116]:
kq4.dot(A_)

matrix([[24., 11., 29.]])

In [117]:
kq5.dot(A_)

matrix([[ 1., 16., 11.]])